### ISSUE TITLE
Menu driven Program In DSA 

### ISSUE THREAD

**Issue by Emsolutions** [Emsolutions/DSA-Menu_driven_program#1]
Write a menu driven program to implement queue operations such asInsert, Delete, Display, whether queue is empty etc by using array

**Comment by ashishgaurav2403** [comment]
assign it to me

**Comment by Rkpani05** [comment]
I would like to contribute please assign me

**Comment by Emsolutions** [comment]
Assigned @ashishgaurav2403  and @Rkpani05 for the task FCFS

**Comment by Emsolutions** [comment]
Good work @Rkpani05
